/**
 * ACORD 127 PDF Generator
 * Generates a filled ACORD 127 Trucking Application Supplement PDF
 *
 * Since ACORD forms are proprietary templates, this generator creates
 * a professional PDF document with all ACORD 127 fields programmatically.
 */

import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';
import type { SmartIntakeData } from '@/types/intake';
import { mapToAcord127, type FieldMapping } from '@/lib/acord-mappings';

/**
 * Generates a filled ACORD 127 PDF
 * @param data SmartIntakeData from the intake form
 * @returns PDF as Uint8Array
 */
export async function generateAcord127(data: SmartIntakeData): Promise<Uint8Array> {
  // Map form data to ACORD 127 field values
  const fields = mapToAcord127(data);

  // Create a new PDF document
  const pdfDoc = await PDFDocument.create();

  // Embed fonts
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  // Page dimensions (letter size)
  const pageWidth = 612;
  const pageHeight = 792;

  // Add first page
  let page = pdfDoc.addPage([pageWidth, pageHeight]);
  let yPosition = pageHeight - 40; // Start from top
  const leftMargin = 40;
  const fontSize = 10;
  const lineHeight = 14;
  const sectionSpacing = 20;

  // Helper function to add text
  const addText = (text: string, x: number, y: number, size: number = fontSize, bold: boolean = false) => {
    page.drawText(text, {
      x,
      y,
      size,
      font: bold ? fontBold : font,
      color: rgb(0, 0, 0),
    });
  };

  // Helper function to add a section header
  const addSectionHeader = (title: string) => {
    if (yPosition < 80) {
      // Add new page if needed
      page = pdfDoc.addPage([pageWidth, pageHeight]);
      yPosition = pageHeight - 40;
    }
    yPosition -= sectionSpacing;
    addText(title, leftMargin, yPosition, 12, true);
    yPosition -= lineHeight + 5;

    // Draw underline
    page.drawLine({
      start: { x: leftMargin, y: yPosition + 2 },
      end: { x: pageWidth - leftMargin, y: yPosition + 2 },
      thickness: 1,
      color: rgb(0, 0, 0),
    });
    yPosition -= 5;
  };

  // Helper function to add a field
  const addField = (label: string, value: string | number | boolean | undefined, indent: number = 0) => {
    if (yPosition < 60) {
      // Add new page if needed
      page = pdfDoc.addPage([pageWidth, pageHeight]);
      yPosition = pageHeight - 40;
    }

    const displayValue = value === undefined || value === null || value === ''
      ? 'N/A'
      : String(value);

    addText(`${label}:`, leftMargin + indent, yPosition, fontSize, false);
    addText(displayValue, leftMargin + indent + 250, yPosition, fontSize, false);
    yPosition -= lineHeight;
  };

  // Helper function to add a Q&A field
  const addQA = (question: string, answer: string | number | boolean | undefined, indent: number = 0) => {
    if (yPosition < 60) {
      page = pdfDoc.addPage([pageWidth, pageHeight]);
      yPosition = pageHeight - 40;
    }

    const displayAnswer = answer === undefined || answer === null || answer === ''
      ? 'N/A'
      : String(answer);

    addText(question, leftMargin + indent, yPosition, fontSize, false);
    addText(displayAnswer, leftMargin + indent + 400, yPosition, fontSize, false);
    yPosition -= lineHeight;
  };

  // ===================
  // HEADER
  // ===================
  addText('ACORD 127 - TRUCKING APPLICATION SUPPLEMENT', leftMargin, yPosition, 14, true);
  yPosition -= lineHeight * 2;
  addText('Form Generated by Panta Smart Intake', leftMargin, yPosition, 9, false);
  yPosition -= lineHeight;
  addText(`Generated: ${new Date().toLocaleDateString('en-US')}`, leftMargin, yPosition, 9, false);
  yPosition -= lineHeight * 2;

  // ===================
  // NAMED INSURED SECTION
  // ===================
  addSectionHeader('NAMED INSURED');
  addField('Named Insured', fields.NamedInsured);
  addField('DOT Number', fields.DOTNumber);
  if (fields.MCNumber) {
    addField('MC Number', fields.MCNumber);
  }

  // ===================
  // GARAGING ADDRESS
  // ===================
  addSectionHeader('GARAGING ADDRESS');
  addField('Address', fields.GaragingAddress);
  addField('City', fields.GaragingCity);
  addField('State', fields.GaragingState);
  addField('ZIP Code', fields.GaragingZIP);

  // ===================
  // OPERATIONS QUESTIONS
  // ===================
  addSectionHeader('OPERATIONS');
  addQA('Q1. Interstate Commerce?', fields.Q1_InterstateCommerce);
  addQA('Q2. Radius of Operation', fields.Q2_RadiusOfOperation);
  addQA('Q3. Vehicle Maintenance Program?', fields.Q3_MaintenanceProgram);

  yPosition -= 5;
  addText('Q4. States of Operation:', leftMargin, yPosition, fontSize, false);
  yPosition -= lineHeight;
  const statesText = String(fields.Q4_StatesOfOperation || 'N/A');
  const statesLines = statesText.match(/.{1,80}/g) || [statesText]; // Wrap at 80 chars
  statesLines.forEach(line => {
    if (yPosition < 60) {
      page = pdfDoc.addPage([pageWidth, pageHeight]);
      yPosition = pageHeight - 40;
    }
    addText(line, leftMargin + 10, yPosition, fontSize, false);
    yPosition -= lineHeight;
  });
  yPosition -= 5;

  addText('Q5. Cargo Types:', leftMargin, yPosition, fontSize, false);
  yPosition -= lineHeight;
  const cargoText = String(fields.Q5_CargoTypes || 'N/A');
  const cargoLines = cargoText.match(/.{1,80}/g) || [cargoText];
  cargoLines.forEach(line => {
    if (yPosition < 60) {
      page = pdfDoc.addPage([pageWidth, pageHeight]);
      yPosition = pageHeight - 40;
    }
    addText(line, leftMargin + 10, yPosition, fontSize, false);
    yPosition -= lineHeight;
  });
  yPosition -= 5;

  addQA('Q6. Fleet Size', fields.Q6_FleetSize);
  addQA('Q7. Hazmat Cargo?', fields.Q7_HazmatCargo);

  if (fields.Q7_HazmatCargo === 'Yes' && fields.Q7a_HazmatTypes) {
    addText('Q7a. Hazmat Types:', leftMargin + 20, yPosition, fontSize, false);
    yPosition -= lineHeight;
    const hazmatText = String(fields.Q7a_HazmatTypes);
    const hazmatLines = hazmatText.match(/.{1,70}/g) || [hazmatText];
    hazmatLines.forEach(line => {
      if (yPosition < 60) {
        page = pdfDoc.addPage([pageWidth, pageHeight]);
        yPosition = pageHeight - 40;
      }
      addText(line, leftMargin + 30, yPosition, fontSize, false);
      yPosition -= lineHeight;
    });
  }

  addQA('Q8. Refrigerated Cargo?', fields.Q8_RefrigeratedCargo);
  if (fields.Q8_RefrigeratedCargo === 'Yes') {
    addQA('Q8a. Reefer Breakdown Coverage?', fields.Q8a_ReeferBreakdown, 20);
  }

  addQA('Q9. Trailer Interchange?', fields.Q9_TrailerInterchange);
  if (fields.Q9_TrailerInterchange === 'Yes') {
    addQA('Q9a. Trailer Count', fields.Q9a_TrailerCount, 20);
    addQA('Q9b. Zones', fields.Q9b_TrailerZones, 20);
    addQA('Q9c. Radius', fields.Q9c_TrailerRadius, 20);
  }

  addQA('Q10. MVR Checks Before Hiring?', fields.Q10_ChecksMVRs);
  addQA('Q11. Family Drivers?', fields.Q11_FamilyDrivers);
  addQA('Q12. Leases On to Other Carrier?', fields.Q12_LeasesOn);
  if (fields.Q12_LeasesOn === 'Yes' && fields.Q12a_MotorCarrier) {
    addQA('Q12a. Motor Carrier', fields.Q12a_MotorCarrier, 20);
  }

  addQA('Q13. New Venture (less than 3 years)?', fields.Q13_NewVenture);
  addQA('Q14. Accidents in Last 3 Years', fields.Q14_Accidents3Years);
  addQA('Q15. Safety Program?', fields.Q15_SafetyProgram);

  if (fields.Q15_SafetyProgram === 'Yes' && fields.Q15a_SafetyComponents) {
    addText('Q15a. Safety Program Components:', leftMargin + 20, yPosition, fontSize, false);
    yPosition -= lineHeight;
    const safetyText = String(fields.Q15a_SafetyComponents);
    const safetyLines = safetyText.match(/.{1,70}/g) || [safetyText];
    safetyLines.forEach(line => {
      if (yPosition < 60) {
        page = pdfDoc.addPage([pageWidth, pageHeight]);
        yPosition = pageHeight - 40;
      }
      addText(line, leftMargin + 30, yPosition, fontSize, false);
      yPosition -= lineHeight;
    });
  }

  addQA('Q17. Telematics/ELD?', fields.Q17_Telematics);
  if (fields.Q17_Telematics === 'Yes') {
    if (fields.Q17a_TelematicsFeatures) {
      addText('Q17a. Telematics Features:', leftMargin + 20, yPosition, fontSize, false);
      yPosition -= lineHeight;
      const telematicsText = String(fields.Q17a_TelematicsFeatures);
      const telematicsLines = telematicsText.match(/.{1,70}/g) || [telematicsText];
      telematicsLines.forEach(line => {
        if (yPosition < 60) {
          page = pdfDoc.addPage([pageWidth, pageHeight]);
          yPosition = pageHeight - 40;
        }
        addText(line, leftMargin + 30, yPosition, fontSize, false);
        yPosition -= lineHeight;
      });
    }
    addQA('Q17b. Fleet Percentage with Telematics', `${fields.Q17b_FleetPercentage}%`, 20);
  }

  // ===================
  // DRIVER SCHEDULE
  // ===================
  addSectionHeader('DRIVER SCHEDULE');

  let hasDrivers = false;
  for (let i = 1; i <= 4; i++) {
    const nameField = `Driver${i}_Name`;
    if (fields[nameField]) {
      hasDrivers = true;
      yPosition -= 5;
      addText(`Driver ${i}:`, leftMargin, yPosition, fontSize, true);
      yPosition -= lineHeight;

      addField('Name', fields[`Driver${i}_Name`], 10);
      addField('Date of Birth', fields[`Driver${i}_DOB`], 10);
      addField('License Number', fields[`Driver${i}_License`], 10);
      addField('State', fields[`Driver${i}_State`], 10);
      addField('Years Experience', fields[`Driver${i}_Experience`], 10);
      addField('Date Hired', fields[`Driver${i}_DateHired`], 10);

      yPosition -= 3;
      addText('Violations (last 3 years):', leftMargin + 10, yPosition, fontSize, false);
      yPosition -= lineHeight;
      const violations = String(fields[`Driver${i}_Violations`] || 'None');
      const violationLines = violations.match(/.{1,70}/g) || [violations];
      violationLines.forEach(line => {
        if (yPosition < 60) {
          page = pdfDoc.addPage([pageWidth, pageHeight]);
          yPosition = pageHeight - 40;
        }
        addText(line, leftMargin + 20, yPosition, fontSize - 1, false);
        yPosition -= lineHeight;
      });

      yPosition -= 3;
      addText('Accidents (last 3 years):', leftMargin + 10, yPosition, fontSize, false);
      yPosition -= lineHeight;
      const accidents = String(fields[`Driver${i}_Accidents`] || 'None');
      const accidentLines = accidents.match(/.{1,70}/g) || [accidents];
      accidentLines.forEach(line => {
        if (yPosition < 60) {
          page = pdfDoc.addPage([pageWidth, pageHeight]);
          yPosition = pageHeight - 40;
        }
        addText(line, leftMargin + 20, yPosition, fontSize - 1, false);
        yPosition -= lineHeight;
      });

      yPosition -= 5;
    }
  }

  if (!hasDrivers) {
    addText('No drivers listed', leftMargin + 10, yPosition, fontSize, false);
    yPosition -= lineHeight;
  }

  // ===================
  // VEHICLE SCHEDULE
  // ===================
  addSectionHeader('VEHICLE SCHEDULE');

  let hasVehicles = false;
  for (let i = 1; i <= 4; i++) {
    const yearField = `Vehicle${i}_Year`;
    if (fields[yearField]) {
      hasVehicles = true;
      yPosition -= 5;
      addText(`Vehicle ${i}:`, leftMargin, yPosition, fontSize, true);
      yPosition -= lineHeight;

      addField('Year', fields[`Vehicle${i}_Year`], 10);
      addField('Make', fields[`Vehicle${i}_Make`], 10);
      addField('Model', fields[`Vehicle${i}_Model`], 10);
      addField('VIN', fields[`Vehicle${i}_VIN`], 10);
      addField('Body Type', fields[`Vehicle${i}_BodyType`], 10);
      addField('GVW', fields[`Vehicle${i}_GVW`], 10);
      addField('Stated Value', fields[`Vehicle${i}_Value`], 10);
      addField('Radius', fields[`Vehicle${i}_Radius`], 10);
      addField('For Hire', fields[`Vehicle${i}_ForHire`], 10);

      yPosition -= 3;
      addText('Garaging Address:', leftMargin + 10, yPosition, fontSize, false);
      yPosition -= lineHeight;
      const garaging = String(fields[`Vehicle${i}_Garaging`] || 'N/A');
      const garagingLines = garaging.match(/.{1,70}/g) || [garaging];
      garagingLines.forEach(line => {
        if (yPosition < 60) {
          page = pdfDoc.addPage([pageWidth, pageHeight]);
          yPosition = pageHeight - 40;
        }
        addText(line, leftMargin + 20, yPosition, fontSize - 1, false);
        yPosition -= lineHeight;
      });

      yPosition -= 3;
      addText('Lienholder:', leftMargin + 10, yPosition, fontSize, false);
      yPosition -= lineHeight;
      const lienholder = String(fields[`Vehicle${i}_Lienholder`] || 'None');
      const lienholderLines = lienholder.match(/.{1,70}/g) || [lienholder];
      lienholderLines.forEach(line => {
        if (yPosition < 60) {
          page = pdfDoc.addPage([pageWidth, pageHeight]);
          yPosition = pageHeight - 40;
        }
        addText(line, leftMargin + 20, yPosition, fontSize - 1, false);
        yPosition -= lineHeight;
      });

      yPosition -= 5;
    }
  }

  if (!hasVehicles) {
    addText('No vehicles listed', leftMargin + 10, yPosition, fontSize, false);
    yPosition -= lineHeight;
  }

  // Note about ACORD 129 if needed
  if (data.vehicles.length > 4) {
    yPosition -= 10;
    addText(`Note: ${data.vehicles.length - 4} additional vehicle(s) listed on ACORD 129 continuation.`,
      leftMargin, yPosition, fontSize, true);
    yPosition -= lineHeight;
  }

  // ===================
  // FOOTER
  // ===================
  yPosition -= sectionSpacing;
  if (yPosition < 80) {
    page = pdfDoc.addPage([pageWidth, pageHeight]);
    yPosition = pageHeight - 40;
  }

  page.drawLine({
    start: { x: leftMargin, y: yPosition },
    end: { x: pageWidth - leftMargin, y: yPosition },
    thickness: 0.5,
    color: rgb(0.5, 0.5, 0.5),
  });
  yPosition -= 15;

  addText('ACORD 127 (2014/01) - Trucking Application Supplement', leftMargin, yPosition, 8, false);
  yPosition -= 10;
  addText('This form is for informational purposes and does not constitute a contract.', leftMargin, yPosition, 8, false);

  // Serialize the PDF to bytes
  const pdfBytes = await pdfDoc.save();

  return pdfBytes;
}

/**
 * Download ACORD 127 PDF in browser
 * @param data SmartIntakeData from the intake form
 * @param businessName Business name for filename
 */
export async function downloadAcord127(data: SmartIntakeData, businessName: string): Promise<void> {
  const pdfBytes = await generateAcord127(data);

  // Create blob and download (convert Uint8Array to compatible type)
  const blob = new Blob([new Uint8Array(pdfBytes)], { type: 'application/pdf' });
  const url = URL.createObjectURL(blob);

  const link = document.createElement('a');
  link.href = url;
  link.download = `ACORD_127_${businessName.replace(/[^a-zA-Z0-9]/g, '_')}.pdf`;
  link.click();

  // Cleanup
  URL.revokeObjectURL(url);
}
