/**
 * ACORD 125 PDF Generator
 * Generates a filled ACORD 125 Commercial Insurance Application PDF
 *
 * Since ACORD forms are proprietary templates, this generator creates
 * a professional PDF document with all ACORD 125 fields programmatically.
 */

import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';
import type { SmartIntakeData } from '@/types/intake';
import { mapToAcord125, type FieldMapping } from '@/lib/acord-mappings';

/**
 * Generates a filled ACORD 125 PDF
 * @param data SmartIntakeData from the intake form
 * @returns PDF as Uint8Array
 */
export async function generateAcord125(data: SmartIntakeData): Promise<Uint8Array> {
  // Map form data to ACORD 125 field values
  const fields = mapToAcord125(data);

  // Create a new PDF document
  const pdfDoc = await PDFDocument.create();

  // Embed fonts
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  // Page dimensions (letter size)
  const pageWidth = 612;
  const pageHeight = 792;

  // Add first page
  let page = pdfDoc.addPage([pageWidth, pageHeight]);
  let yPosition = pageHeight - 40; // Start from top
  const leftMargin = 40;
  const fontSize = 10;
  const lineHeight = 14;
  const sectionSpacing = 20;

  // Helper function to add text
  const addText = (text: string, x: number, y: number, size: number = fontSize, bold: boolean = false) => {
    page.drawText(text, {
      x,
      y,
      size,
      font: bold ? fontBold : font,
      color: rgb(0, 0, 0),
    });
  };

  // Helper function to add a section header
  const addSectionHeader = (title: string) => {
    if (yPosition < 80) {
      // Add new page if needed
      page = pdfDoc.addPage([pageWidth, pageHeight]);
      yPosition = pageHeight - 40;
    }
    yPosition -= sectionSpacing;
    addText(title, leftMargin, yPosition, 12, true);
    yPosition -= lineHeight + 5;

    // Draw underline
    page.drawLine({
      start: { x: leftMargin, y: yPosition + 2 },
      end: { x: pageWidth - leftMargin, y: yPosition + 2 },
      thickness: 1,
      color: rgb(0, 0, 0),
    });
    yPosition -= 5;
  };

  // Helper function to add a field
  const addField = (label: string, value: string | number | boolean | undefined, indent: number = 0) => {
    if (yPosition < 60) {
      // Add new page if needed
      page = pdfDoc.addPage([pageWidth, pageHeight]);
      yPosition = pageHeight - 40;
    }

    const displayValue = value === undefined || value === null || value === ''
      ? 'N/A'
      : String(value);

    addText(`${label}:`, leftMargin + indent, yPosition, fontSize, false);
    addText(displayValue, leftMargin + indent + 200, yPosition, fontSize, false);
    yPosition -= lineHeight;
  };

  // Helper function to add checkbox
  const addCheckbox = (label: string, checked: boolean, xPos: number) => {
    if (yPosition < 60) {
      page = pdfDoc.addPage([pageWidth, pageHeight]);
      yPosition = pageHeight - 40;
    }

    // Draw checkbox square
    const boxSize = 8;
    page.drawRectangle({
      x: xPos,
      y: yPosition - 2,
      width: boxSize,
      height: boxSize,
      borderColor: rgb(0, 0, 0),
      borderWidth: 1,
    });

    // Draw checkmark if checked
    if (checked) {
      addText('✓', xPos + 1, yPosition - 1, fontSize, true);
    }

    // Add label
    addText(label, xPos + boxSize + 5, yPosition, fontSize, false);
  };

  // ===================
  // HEADER
  // ===================
  addText('ACORD 125 - COMMERCIAL INSURANCE APPLICATION', leftMargin, yPosition, 14, true);
  yPosition -= lineHeight * 2;
  addText('Form Generated by Panta Smart Intake', leftMargin, yPosition, 9, false);
  yPosition -= lineHeight;
  addText(`Generated: ${new Date().toLocaleDateString('en-US')}`, leftMargin, yPosition, 9, false);
  yPosition -= lineHeight * 2;

  // ===================
  // NAMED INSURED SECTION
  // ===================
  addSectionHeader('NAMED INSURED');
  addField('Legal Name', fields.NamedInsured);
  if (fields.DBA) {
    addField('DBA', fields.DBA);
  }
  addField('Mailing Address', fields.MailingAddress);
  addField('City', fields.City);
  addField('State', fields.State);
  addField('ZIP Code', fields.ZIP);
  addField('Phone', fields.Phone);
  if (fields.Website) {
    addField('Website', fields.Website);
  }
  addField('FEIN', fields.FEIN);

  // ===================
  // ENTITY TYPE
  // ===================
  yPosition -= 10;
  addText('Entity Type:', leftMargin, yPosition, fontSize, true);
  yPosition -= lineHeight + 5;

  let checkboxX = leftMargin + 20;
  addCheckbox('Individual', fields.Individual as boolean, checkboxX);
  checkboxX += 100;
  addCheckbox('Partnership', fields.Partnership as boolean, checkboxX);
  checkboxX += 110;
  addCheckbox('Corporation', fields.Corporation as boolean, checkboxX);
  yPosition -= lineHeight;

  checkboxX = leftMargin + 20;
  addCheckbox('LLC', fields.LLC as boolean, checkboxX);
  checkboxX += 100;
  addCheckbox('Other', fields.Other as boolean, checkboxX);
  yPosition -= lineHeight + 5;

  // ===================
  // BUSINESS INFORMATION
  // ===================
  addSectionHeader('BUSINESS INFORMATION');
  addField('Years in Business', fields.YearsInBusiness);
  addField('Annual Revenue', fields.AnnualRevenue);
  addField('Full-Time Employees', fields.FullTimeEmployees);
  addField('Part-Time Employees', fields.PartTimeEmployees);

  // ===================
  // OPERATIONS DESCRIPTION
  // ===================
  addSectionHeader('DESCRIPTION OF OPERATIONS');
  addField('DOT Number', fields.DOTNumber);
  if (fields.MCNumber) {
    addField('MC Number', fields.MCNumber);
  }

  // Handle multi-line description
  yPosition -= 5;
  addText('Operations:', leftMargin, yPosition, fontSize, true);
  yPosition -= lineHeight;
  const description = String(fields.DescriptionOfOperations || 'N/A');
  const descLines = description.split('\n');
  descLines.forEach(line => {
    if (yPosition < 60) {
      page = pdfDoc.addPage([pageWidth, pageHeight]);
      yPosition = pageHeight - 40;
    }
    addText(line, leftMargin + 10, yPosition, fontSize, false);
    yPosition -= lineHeight;
  });

  // ===================
  // PRIOR INSURANCE
  // ===================
  addSectionHeader('PRIOR INSURANCE');
  addField('Currently Insured', fields.CurrentlyInsured);
  if (fields.CurrentlyInsured === 'Yes') {
    addField('Prior Carrier', fields.PriorCarrier);
    addField('Policy Number', fields.PolicyNumber);
    addField('Effective Date', fields.EffectiveDate);
    addField('Expiration Date', fields.ExpirationDate);
    addField('Annual Premium', fields.AnnualPremium);
  }

  // ===================
  // COVERAGE REQUESTED
  // ===================
  addSectionHeader('COVERAGE REQUESTED');
  addField('Liability Limit', fields.LiabilityLimit);
  addField('Comprehensive Deductible', fields.ComprehensiveDeductible);
  addField('Collision Deductible', fields.CollisionDeductible);
  addField('Hired Auto Coverage', fields.HiredAuto);
  addField('Non-Owned Auto Coverage', fields.NonOwnedAuto);

  // ===================
  // LINES OF BUSINESS
  // ===================
  yPosition -= 10;
  addText('Lines of Business:', leftMargin, yPosition, fontSize, true);
  yPosition -= lineHeight + 5;

  checkboxX = leftMargin + 20;
  addCheckbox('Truckers', fields.Truckers as boolean, checkboxX);
  checkboxX += 100;
  addCheckbox('Motor Carrier', fields.MotorCarrier as boolean, checkboxX);
  yPosition -= lineHeight + 5;

  // ===================
  // LOSS HISTORY
  // ===================
  addSectionHeader('LOSS HISTORY (LAST 5 YEARS)');

  let hasLosses = false;
  for (let i = 1; i <= 5; i++) {
    const dateField = `LossClaim${i}_Date`;
    if (fields[dateField]) {
      hasLosses = true;
      yPosition -= 5;
      addText(`Claim ${i}:`, leftMargin, yPosition, fontSize, true);
      yPosition -= lineHeight;

      addField('Date of Loss', fields[`LossClaim${i}_Date`], 10);
      addField('Type', fields[`LossClaim${i}_Type`], 10);
      addField('Amount Paid', fields[`LossClaim${i}_AmountPaid`], 10);
      addField('Amount Reserved', fields[`LossClaim${i}_AmountReserved`], 10);
      addField('Description', fields[`LossClaim${i}_Description`], 10);
      yPosition -= 5;
    }
  }

  if (!hasLosses) {
    addText('No claims in the last 5 years', leftMargin + 10, yPosition, fontSize, false);
    yPosition -= lineHeight;
  }

  // ===================
  // KNOCKOUT QUESTIONS (All should be "No")
  // ===================
  addSectionHeader('UNDERWRITING QUESTIONS');
  addField('Has operating authority ever been revoked/suspended?', fields.AuthorityRevoked);
  addField('Is DOT safety rating Unsatisfactory?', fields.SafetyRatingUnsatisfactory);
  addField('Has any driver had license revoked (last 3 years)?', fields.DriverLicenseRevoked);
  addField('Any conviction for fraud or misrepresentation?', fields.FraudConviction);
  addField('Bankruptcy filed (last 5 years)?', fields.BankruptcyFiled);
  addField('Insurance cancelled for non-payment (last 3 years)?', fields.InsuranceCancelled);

  // ===================
  // FOOTER
  // ===================
  yPosition -= sectionSpacing;
  if (yPosition < 80) {
    page = pdfDoc.addPage([pageWidth, pageHeight]);
    yPosition = pageHeight - 40;
  }

  page.drawLine({
    start: { x: leftMargin, y: yPosition },
    end: { x: pageWidth - leftMargin, y: yPosition },
    thickness: 0.5,
    color: rgb(0.5, 0.5, 0.5),
  });
  yPosition -= 15;

  addText('ACORD 125 (2016/03) - Commercial Insurance Application', leftMargin, yPosition, 8, false);
  yPosition -= 10;
  addText('This form is for informational purposes and does not constitute a contract.', leftMargin, yPosition, 8, false);

  // Serialize the PDF to bytes
  const pdfBytes = await pdfDoc.save();

  return pdfBytes;
}

/**
 * Download ACORD 125 PDF in browser
 * @param data SmartIntakeData from the intake form
 * @param businessName Business name for filename
 */
export async function downloadAcord125(data: SmartIntakeData, businessName: string): Promise<void> {
  const pdfBytes = await generateAcord125(data);

  // Create blob and download (convert Uint8Array to compatible type)
  const blob = new Blob([new Uint8Array(pdfBytes)], { type: 'application/pdf' });
  const url = URL.createObjectURL(blob);

  const link = document.createElement('a');
  link.href = url;
  link.download = `ACORD_125_${businessName.replace(/[^a-zA-Z0-9]/g, '_')}.pdf`;
  link.click();

  // Cleanup
  URL.revokeObjectURL(url);
}
